### ISSUE TITLE
ODF Prerequisites

### ISSUE THREAD

**Issue by HammerMeetNail** [red-hat-storage/odf-operator#195]
Does ODF require multiple nodes like [OCS](https://github.com/red-hat-storage/ocs-operator#prerequisites)? Trying to install on a single node Microshift instance and bumping into errors. 

If it does require multiple nodes, is there any workaround to allow for a single node?

**Comment by iamniting** [comment]
Hello @HammerMeetNail 

Yes, it does require multiple nodes as internally it uses a storagecluster (ceph) itself.

**Comment by HammerMeetNail** [comment]
Thanks @iamniting
