### ISSUE TITLE
Tried to deploy and use odf operator in okd 4.10 & vsphere 6.7

### ISSUE THREAD

**Issue by johnlongo** [red-hat-storage/odf-operator#210]
Tried to deploy and use odf operator in okd 4.10 & vsphere 6.7. The deployment worked fine, I was able to create a storage cluster. But when I tried to use the odf storage class my pods could not write to the pvc that was created.  Do I need to add a security role to the pod for it to be able to write to the pvc. Any help you can give will be appreciated.

**Comment by iamniting** [comment]
@travisn Can you pls suggest?

**Comment by travisn** [comment]
@johnlongo Was the volume mounted to the app pod? You just can't write to it? What is the error? From your brief description it does sound like you need a securityContext for the pod. As a quick workaround, you could start by adding a privileged security context, then figure out a more restrictive context as needed.

**Comment by johnlongo** [comment]
Thank you for the response, I'll give that a try and respond back,

**Comment by johnlongo** [comment]
btw the error I was getting was access denied

**Comment by johnlongo** [comment]
TY
