### ISSUE TITLE
No documentation for deploying all side components

### ISSUE THREAD

**Issue by gerardo8a** [red-hat-storage/odf-operator#266]
I would like to install all the ODF components via CLI. What would be the way to install all components that get installed when using the market place if I want to install them via CLI?

I would like to do this for CI purposes, Readme.md only mentione installing the ODF it self but comparing what it gets installed in the cluster via marketplace is not the same as some components are missing. Not sure about every detail of what needs to be installed, but at least looking at the pods I see the rook-ceph, console, noobaa, csi-addons, odf-console, ocs-metrics, odf-operator-controller-manager etc.

This is more of lack of documentation or guidance than an issue, so I appreciate if there is any guidance I could look at so I can create all this my self and avoid going through the web UI

Thanks!

**Comment by gerardo8a** [comment]
There was a miss match with the versions, I used 4.11.2 in channel alpha but I had to use the latest in the repo 4.12.0

**Comment by iamniting** [comment]
Hello @gerardo8a Are you building from the source code yourself? If you haven't already, I strongly suggest you to do so. This tutorial will assist you in accomplishing that.

* https://github.com/red-hat-storage/odf-operator#deploying-development-builds
