### ISSUE TITLE
Updating ODF operator doesn't reboot mds, mgr and mon pods

### ISSUE THREAD

**Issue by cancestlamort** [red-hat-storage/odf-operator#291]
Hello, 

I don't know whether to classify it as an "issue" but I'm very curious, when updating the ODF operator within my Openshift cluster, I notice that the MDS, MGR, and MON pods are not restarted automatically.

All pods except MON, MGR and MDS were automatically rebooted with the update:

csi-cephfsplugin
csi-cephfsplugin-provisioner
csi-rbdplugin
csi-rbdplugin-provisioner
noobaa-core-0
noobaa-db-pg-0
noobaa-endpoint
odf-console
rook-ceph-crashcollector
rook-ceph-osd
rook-ceph-rgw-ocs-storagecluster-cephobjectstore
rook-ceph-tools

See attached file the age difference of operator pods vs mon, mgr and mds pods

I have updated the ODF operator many times and I see this behavior, as I said before, I don't know if it is an issue but I ask you the reason why these pods don't restart.

Is it necessary to restart only these pods manually?

For some reason, at the time of the update, the operator does not touch these pods.

Thanks in advance.
![odf operator pods age](https://user-images.githubusercontent.com/125225469/218346447-9021e1f7-7de0-4eac-8181-b513826239b2.jpg)

**Comment by iamniting** [comment]
Good day, @cancestlamort.

The rook operator manages the mon, mds, and mgr pods. They will be restarted only if the image or other manifests have changed during the reconciliation process. which might not have taken place. I don't believe we need to restart them manually.

**Comment by cancestlamort** [comment]
Hello , thank you for your reply.

What scenario can the image or manifests change during the reconciliation process?

Let me know you feedback. Regards
