### ISSUE TITLE
Create OBC with predefined credentials

### ISSUE THREAD

**Issue by alexknobel** [red-hat-storage/odf-operator#323]
Hi,

Is it possible to create OBC and provide bucket name, credentials manually instead of generating automatically (access key, secret key)?

Thanks,
Alex

**Comment by parth-gr** [comment]
Related to https://github.com/rook/rook/issues/11563 https://github.com/rook/rook/pull/11336

I guess it needs Rook changes.

**Comment by iamniting** [comment]
@alexknobel I hope all your queries are sorted in the chat. If yes can we pls close the issue?
